### ISSUE TITLE
怎么添加管理员？

### ISSUE THREAD

**Issue by notepaper** [wowwm/MessageBoard-MiniProgram#1]
如题！

**Comment by notepaper** [comment]
错误一
VM851:1 Uncaught (in promise) thirdScriptError
Cannot read property 'data' of null
TypeError: Cannot read property 'data' of null
    at http://127.0.0.1:31276/appservice/pages/index/index.js:52:30
console.error @ VM851:1
errorReport @ VM867 WAService.js:2
thirdErrorReport @ VM867 WAService.js:2
(anonymous) @ VM867 WAService.js:2
c @ VM867 WAService.js:2
i @ VM867 WAService.js:2
(anonymous) @ VM867 WAService.js:2
value @ VM867 WAService.js:2
t @ VM867 WAService.js:2
(anonymous) @ VM867 WAService.js:2
VM851:1 Uncaught (in promise) thirdScriptError
Cannot read property '_openid' of undefined
TypeError: Cannot read property '_openid' of undefined
    at http://127.0.0.1:31276/appservice/pages/index/index.js:69:50
console.error @

错误2
 VM851:1
errorReport @ VM867 WAService.js:2
thirdErrorReport @ VM867 WAService.js:2
(anonymous) @ VM867 WAService.js:2
c @ VM867 WAService.js:2
i @ VM867 WAService.js:2
(anonymous) @ VM867 WAService.js:2
value @ VM867 WAService.js:2
t @ VM867 WAService.js:2
(anonymous) @ VM867 WAService.js:2

**Comment by wowwm** [comment]
在云开发数据库建了一个author集合，里面放了我自己的openid，每次页面加载时检查当前用户openid是否和author一致。

**Comment by Tablezhuozhuo** [comment]
我添加了author集合  还是报上面的错 是怎么回事呢？
