### ISSUE TITLE
按你的步骤部署好之后显示只有管理员才能新建留言板

### ISSUE THREAD

**Issue by pearandli** [wowwm/MessageBoard-MiniProgram#2]
我通过这个教程https://blog.csdn.net/qiushi_1990/article/details/83015910 获取到了自己的openid，在author里面添加了一个字段openid，但是运行后还是遇到如下报错，请问一下是哪里有问题？
提示：WAService.js:1 Uncaught (in promise) Error: errCode: -404011 cloud function execution error | errMsg: cloud.callFunction:fail requestID , cloud function service error code -501000, error message 找不到对应的FunctionName.; at cloud.callFunction api; 
    at new u (WAService.js:1)
    at d (WAService.js:1)
    at f (WAService.js:1)
    at Function.success (WAService.js:1)
    at WAService.js:1
    at C (WAService.js:1)
    at i.<anonymous> (WAService.js:1)
    at i.emit (WAService.js:1)
    at Rs (WAService.js:1)
    at WAService.js:1
u @ WAService.js:1
d @ WAService.js:1
f @ WAService.js:1
success @ WAService.js:1
(anonymous) @ WAService.js:1
C @ WAService.js:1
(anonymous) @ WAService.js:1
i.emit @ WAService.js:1
Rs @ WAService.js:1
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
o @ VM3459 asdebug.js:1
(anonymous) @ VM3459 asdebug.js:1
t.emit @ VM3459 asdebug.js:1
callback @ VM3459 asdebug.js:1
(anonymous) @ VM3459 asdebug.js:1
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
Promise.then (async)
getData @ index.js:47
onLoad @ index.js:82
(anonymous) @ WAService.js:1
p.__callPageLifeTime__ @ WAService.js:1
Tt @ WAService.js:1
(anonymous) @ WAService.js:1
xt @ WAService.js:1
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
i.emit @ WAService.js:1
emit @ WAService.js:1
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
o @ VM3459 asdebug.js:1
(anonymous) @ VM3459 asdebug.js:1
(anonymous) @ VM3459 asdebug.js:1
_ws.onmessage @ VM3459 asdebug.js:1
index.js:63 Uncaught (in promise) TypeError: Cannot read property 'openid' of undefined
    at index.js:63

**Comment by testerzhang** [comment]
那是你没有同步到云函数吧
